image: gitpod/workspace-python:2022-10-10-01-40-34

tasks:
  - init: make prepare

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
