image:
  file: .gitpod.Dockerfile

tasks:
  - init: python3 -m pip install -U -r requirements_dev.txt &&
          python3 -m pip install --upgrade pip

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
