 tasks:
  - init: go env -w GO111MODULE=off &&
          go get github.com/devlights/mkghurl &&
          go env -u GO111MODULE &&
          if [ -n "$GITHUB_TOKEN" ]; then git remote set-url origin $(mkghurl try-python); fi
    command: python3 -V
image:
  file: .gitpod.Dockerfile
