name: trypython
channels:
- conda-forge
- defaults
dependencies:
- autopep8
- blinker
- ciso8601
- ftputil
- ipython
- joblib
- openpyxl
- pandas
- paramiko
- pip
- pygments
- pyqt
- psutil
- pyperclip
- pytest
- python
- python-dateutil
- pyyaml
- pyzmq
- raven
- redis
- requests
- texttable
- tqdm
- pip:
  - bitstring
  - icecream
