name: trypython
channels:
- defaults
dependencies:
- beautifulsoup4
- ipython
- joblib
- lxml
- openpyxl
- paramiko
- pip
- psutil
- pyqt
- pytest
- python
- pyyaml
- pyzmq
- requests
- sqlalchemy
- tqdm
- pip:
  - bitstring
  - ftputil
  - pyperclip
  - records
  - redis
  - rx
  - tablib
  - texttable
