name: trypython
channels:
- defaults
dependencies:
- appnope=0.1.0=py36_0
- asn1crypto=0.22.0=py36_0
- beautifulsoup4=4.6.0=py36_0
- certifi=2016.2.28=py36_0
- cffi=1.10.0=py36_0
- cryptography=1.8.1=py36_0
- decorator=4.1.2=py36_0
- et_xmlfile=1.0.1=py36_0
- icu=54.1=0
- idna=2.6=py36_0
- ipython=6.1.0=py36_0
- ipython_genutils=0.2.0=py36_0
- jdcal=1.3=py36_0
- jedi=0.10.2=py36_2
- joblib=0.11=py36_0
- libiconv=1.14=0
- libxml2=2.9.4=0
- libxslt=1.1.29=0
- lxml=3.8.0=py36_0
- openpyxl=2.4.8=py36_0
- openssl=1.0.2l=0
- packaging=16.8=py36_0
- paramiko=2.1.2=py36_0
- path.py=10.3.1=py36_0
- pexpect=4.2.1=py36_0
- pickleshare=0.7.4=py36_0
- pip=9.0.1=py36_1
- prompt_toolkit=1.0.15=py36_0
- psutil=5.2.2=py36_0
- ptyprocess=0.5.2=py36_0
- py=1.4.34=py36_0
- pyasn1=0.2.3=py36_0
- pycparser=2.18=py36_0
- pygments=2.2.0=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_2
- pytest=3.2.1=py36_0
- python=3.6.2=0
- pyyaml=3.12=py36_0
- pyzmq=16.0.2=py36_0
- qt=5.6.2=2
- readline=6.2=2
- redis=3.2.0=0
- requests=2.14.2=py36_0
- setuptools=36.4.0=py36_1
- simplegeneric=0.8.1=py36_1
- sip=4.18=py36_0
- six=1.10.0=py36_0
- sqlalchemy=1.1.13=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- tqdm=4.15.0=py36_0
- traitlets=4.3.2=py36_0
- wcwidth=0.1.7=py36_0
- wheel=0.29.0=py36_0
- xz=5.2.3=0
- yaml=0.1.6=0
- zlib=1.2.11=0
- pip:
  - bitstring==3.1.5
  - docopt==0.6.2
  - et-xmlfile==1.0.1
  - ftputil==3.3.1
  - ipython-genutils==0.2.0
  - odfpy==1.3.5
  - prompt-toolkit==1.0.15
  - pyperclip==1.5.27
  - records==0.5.2
  - rx==1.6.0
  - tablib==0.12.1
  - texttable==0.9.1
  - unicodecsv==0.14.1
  - xlrd==1.1.0
  - xlwt==1.3.0
