name: trypython
channels:
- defaults
- conda-forge
dependencies:
- autopep8
- ipython
- joblib
- openpyxl
- paramiko
- pip
- pyqt
- psutil
- pytest
- python
- pyyaml
- pyzmq
- requests
- tqdm
- pip:
  - bitstring
  - ftputil
  - pyperclip
  - redis
  - texttable
