version: '3'

tasks:
  default:
    cmds:
      - task: run
  repl:
    cmds:
      - uv run python
  run:
    cmds:
      - uv run python -m trypython
  fmt:
    cmds:
      - uv run ruff format .
  lint:
    cmds:
      - cmd: uv run ruff check .
        ignore_error: true
  typecheck:
    cmds:
      - cmd: uv run ty check
        ignore_error: true
  test:
    cmds:
      - cmd: uv run pytest
        ignore_error: true
